fig4 updates
Princeton-CDH/startwords pull request #365
Opened 2023-09-21 23:57 UTC by thatbudakguy

- Update figure 4 text and styling
- Switch to light color theme
- Complete styling for figure 4

2023-09-22 13:18 UTC, rlskoeser requested changes
Lighthouse is complaining about `aria-description`; did you mean to use `aria-label`? Seems like your description is short enough for a label.  

The adjustment of the table width for desktop didn't look like it was working; I'm suggesting a change to set a max-width on the caption as well as the table, which I think resolves the problem.

The other changes look fine to me.

2023-09-22 13:18 UTC, rlskoeser commented on content/issues/4/sonorous-medieval/style.css
> +    font-size: 1.25rem;
I think setting a max-width on the caption fixes the table alignment on desktop.

```suggestion
    font-size: 1.25rem;
    max-width: 32rem;
```

2023-09-22 18:01 UTC, thatbudakguy commented
I set `aria-description` because I didn't want to override the label (which is just the content of the sound), but just add some extra context for non-sighted users (i.e. that it's rhyming). VO reads it as "rhyming sound, [transcription]" instead of just "[transcription]" which seemed better to me 🤷🏻 

That said, getting anything useful at all out of these transcriptions might be a losing battle...SRs really mangle them (some of them, inexplicably, seem to be read in a russian-sounding voice??) and there's no `lang=` attribute code that you can use to hint at what voice algorithm because...IPA and other systems aren't a language! so I'd be OK doing something else (or nothing) too.

2023-09-22 18:03 UTC, rlskoeser commented
> That said, getting anything useful at all out of these transcriptions might be a losing battle...SRs really mangle them (some of them, inexplicably, seem to be read in a russian-sounding voice??) and there's no `lang=` attribute code that you can use to hint at what voice algorithm because...IPA and other systems aren't a language! so I'd be OK doing something else (or nothing) too.

Yeah, I was wondering how this would be made accessible... I wonder if an extended description would be a different way to approach this?

2023-09-22 18:03 UTC, thatbudakguy commented
That's probably the right call! I'll draft something and get it in this PR.

2023-09-22 19:31 UTC, thatbudakguy commented
ok, I kept it simple: just added some additional SR-only explanation to the `<caption>` for both table describing the key insight in more detail.

2023-09-22 20:11 UTC, rlskoeser approved these changes

2023-09-22 20:11 UTC, merged

2023-09-25 17:53 UTC, gwijthoff commented
@thatbudakguy the new caption is _perfect_, thank you!